Kernel optimisations
DiamondLightSource/fast-feedback-service pull request #19
Opened 2024-12-02 16:33 UTC by dimitrivlachos

Optimise CUDA kernels with shared and constant memory

Up until now, we have been using a naive memory access pattern in our 
CUDA kernels, relying on global memory and automatic caching to store 
and retrieve data. While this was functional and fairly performant, we 
can improve kernel efficiency by utilising CUDA's optimised methods for
managing memory access.

This refactors all CUDA kernels to:
- Use shared memory to chunk data into smaller, shared blocks.
- Use constant memory to store frequently used, constant data in an 
  aggressively cached state.

These changes reduce kernel runtime and memory usage, optimising 
performance and allowing us to focus on other areas of the application.

Create a new common header (`device_common`) for device-specific 
functions, structs, and constants. This improves readability and eases 
maintenance for repetitive tasks.

Enable multi-file CUDA compilation to allow global constants to be 
shared across files.

Closes #12

2024-12-06 16:34 UTC, dimitrivlachos commented
### Profiling provides the following insights:

# Dispersion
`Dispersion` runs ~15% faster.
![image](https://github.com/user-attachments/assets/33b78da2-82aa-4fba-b1eb-754b095df88c)

However, occupancy has been reduced due to additional register usage
![image](https://github.com/user-attachments/assets/6dd0da52-4424-438d-b503-527198277958)

# Extended Dispersion
`extended_dispersion` runs ~13% faster

| Baseline | Optimised |
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/a7d3466e-b649-4870-b464-022a9329576a) | ![image](https://github.com/user-attachments/assets/a6458d83-9b35-4f45-9ce6-27c300ad038d) |

It is interesting to note that `erosion` is actually _slower_ using these optimisations. So it may be worth reverting these changes before merging, though its runtime is still very short by comparison.

Both the first and second passes benefit largely from these changes. The first pass suffers from the same occupancy drop as one-pass `dispersion`, however, the second pass does not, likely owing to the fact that regular `dispersion` and the first pass of `extended dispersion` utilise a lot of shared code. So addressing this should address both kernels.

# Summary
These changes provide a roughly **_15%_** decrease in kernel execution time, now that we are using more optimal memory accesses.

2025-01-14 16:05 UTC, dimitrivlachos commented
@ndevenish is this more acceptable? 😄

2025-01-17 08:58 UTC, ndevenish requested changes

2025-01-17 08:58 UTC, ndevenish commented on spotfinder/spotfinder.cu
> +    * shared_block_width * 1shared_block_height0 * (sizeof(int) + sizeof(float) + sizeof(double))
```suggestion
    * shared_block_width * shared_block_height * (sizeof(int) + sizeof(float) + sizeof(double))
```
`1shared_block_height0` ?

2025-01-22 13:43 UTC, jbeilstenedmands commented
This PR currently fails the `dispersion_extended.sh` test but not the `regular_dispersion.sh` test.
I looked at the code and it looks like the erosion mask is not being created and used correctly in the erosion kernel and second pass.
I think this is the fix:
https://github.com/DiamondLightSource/fast-feedback-service/compare/kernel_optimisations...jbeilstenedmands:fast-feedback-service:kernel_optimisations
the test passes, although I may have missed something with regards to shared memory use. We probably want to re-profile after the fix to check we still get performance improvements?

2025-01-22 15:25 UTC, dimitrivlachos commented
I have also re-profiled the repo as it stands right now at [0582f84](https://github.com/DiamondLightSource/fast-feedback-service/pull/19/commits/0582f843d222949e3faade0b4c00bcbd3b866b1f)

| Baseline | Optimised |
| ----- | ----- |
| ![image](https://github.com/user-attachments/assets/d576f595-f37c-40b7-9f9e-83f3ef5b7b83) | ![image](https://github.com/user-attachments/assets/69071abe-82cc-41e0-9ad7-a021b42f6b57) |
|Duration: 3.79ɥs|Duration: 3.03ɥs|

Still ~20% faster in this particular case, especially for the second pass.

2025-01-22 15:27 UTC, dimitrivlachos commented
@jbeilstenedmands @ndevenish Should I revert `erosion` to the naïve implementation as it was before? This would be the fastest option then, but it will then diverge slightly to the pattern of the other kernels.

Though considering this PR _is_ in fact about optimisations I am leaning in that direction.

2025-01-22 16:23 UTC, dimitrivlachos commented
Now we are optimised 👌

![image](https://github.com/user-attachments/assets/a1783733-c6e7-4e2c-a7e4-5e64e0153482)

~2.91ɥs runtime, for a total of ~23% speed-up in this case.

2025-01-23 11:13 UTC, ndevenish approved these changes

2025-01-23 11:19 UTC, merged